spring:
  profiles: local-development
  datasource:
    url: ${sbac.jdbc.host}/configs
    username: ${sbac.jdbc.user}
    password: ${sbac.jdbc.password}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: false
  resources:
    add-mappings: false

flyway:
  enabled: false

server:
  port: 8083
  undertow:
    buffer-size: 16384
    buffers-per-region: 20
    io-threads: 64
    worker-threads: 512
    direct-buffers: true